# Generated by Django 5.1.3 on 2024-11-19 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=16)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('Grooming', 'Grooming'), ('In progress', 'In progress'), ('Dev', 'Dev'), ('Done', 'Done')], max_length=16)),
                ('priority', models.CharField(choices=[('Low', 'Низкий'), ('Medium', 'Средний'), ('High', 'Высокий')], default='Medium', max_length=16)),
                ('create_date', models.DateField(auto_now_add=True)),
                ('last_update_date', models.DateField(auto_now=True)),
                ('deadline', models.DateField()),
            ],
        ),
    ]
