# Generated by Django 5.1.3 on 2024-11-13 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('projectURL', models.URLField(default='https://api/v1/user/project/')),
                ('title', models.CharField(max_length=64)),
                ('description', models.TextField()),
                ('date_of_creation', models.DateTimeField(auto_now_add=True)),
                ('date_of_update', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(default='active', max_length=64)),
            ],
        ),
    ]
