# Generated by Django 5.1.3 on 2024-11-13 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='projectURL',
            field=models.URLField(blank=True, default='https://api/v1/'),
        ),
    ]
