# Generated by Django 5.1.3 on 2024-11-13 17:26

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_defaultuser_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='defaultuser',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='defaultuser',
            name='password',
            field=models.CharField(max_length=128),
        ),
    ]
