# Generated by Django 5.1.3 on 2024-11-13 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_defaultuser_id_alter_defaultuser_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='defaultuser',
            name='password',
            field=models.CharField(max_length=128, verbose_name='password'),
        ),
    ]
