# Generated by Django 5.1.3 on 2024-11-13 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_alter_project_projecturl'),
        ('user', '0004_alter_defaultuser_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='defaultuser',
            name='projects',
            field=models.ManyToManyField(blank=True, null=True, to='project.project'),
        ),
    ]
